Update snyk-container.yml

diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -48,7 +48,14 @@ jobs:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         image: your/image-to-test
-        args: --file=Dockerfile --sarif-file-output=snyk.sarif
+        args: --file=Dockerfile
+    - name: Validate SARIF file
+      run: |
+        jq '.runs[].results[] | select(.ruleId == null or .level == null)' snyk.sarif
+        if [ $? -eq 0 ]; then
+          echo "SARIF file contains invalid entries."
+          exit 1
+        fi
     - name: Upload result to GitHub Code Scanning
       uses: github/codeql-action/upload-sarif@v2
       with:
